'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from '@ant-design/icons';
import { Layout, Menu, Button, theme } from 'antd';
import { useState } from 'react'

const { Header, Sider, Content } = Layout;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [collapsed, setCollapsed] = useState(false);
  const {
    token: { colorBgContainer },
  } = theme.useToken();




  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar></Navbar>
        </header>

        <Layout>
          <Sider trigger={null} collapsible collapsed={collapsed}>
            <div className="demo-logo-vertical" />
            <Menu
              theme="dark"
              mode="inline"
              defaultSelectedKeys={['1']}
              items={[
                {
                  key: '1',
                  icon: <UserOutlined />,
                  label: 'Feed',
                },
                {
                  key: '2',
                  icon: <VideoCameraOutlined />,
                  label: 'Appreciate',
                },
                {
                  key: '3',
                  icon: <UploadOutlined />,
                  label: 'Badge',
                },
                {
                  key: '4',
                  icon: <UserOutlined />,
                  label: 'Profile',
                },
              ]}
            />
          </Sider>
          <Layout>
            <Header style={{ padding: 0, background: colorBgContainer }}>
              <Button
                type="text"
                icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
                onClick={() => setCollapsed(!collapsed)}
                style={{
                  fontSize: '16px',
                  width: 64,
                  height: 64,
                }}
              />
            </Header>
            <Content
              style={{
                margin: '24px 16px',
                padding: 24,
                minHeight: 280,
                background: colorBgContainer,
              }}
            >
              {children}
            </Content>
          </Layout>
          <Sider collapsed>
            <div className="demo-logo-vertical" />
            <Menu
              theme="dark"
              mode="inline"
              defaultSelectedKeys={['1']}
              items={[
                {
                  key: '1',
                  icon: <UserOutlined />,
                  label: 'SALT',
                },
                {
                  key: '2',
                  icon: <VideoCameraOutlined />,
                  label: 'Settings',
                },
                {
                  key: '3',
                  icon: <VideoCameraOutlined />,
                  label: 'Help',
                },
              ]}
            />
          </Sider>
        </Layout>
      </body>
    </html>
  )
}
