import Navbar from '@/componenets/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
        <Navbar></Navbar>
      </header> 

       {/* <--- Left Side bar--> */}
       <div className="side-bar">
        <Link href={'/home'}>Feed</Link>
        <Link href={'/appreciate'}>Appreciate</Link>
        <Link href={'/badges'}>Badges</Link>
        <Link href={'/profile'}>Profile</Link>
        </div>

       {/* <--- Right Side bar--> */}
       <div className='side-bar'>
        <Link href={'/home'}>Salt</Link>
        <Link href={'/editprofile'}><img src=""
        ></img>Settings</Link>
         <Link href={'/help'}><img src=""
        ></img>Help</Link>
       </div>
        {children}
      </body>
    </html>
  )
}
